### ISSUE TITLE
Ctrl + Shift + I is a core shortcut on linux

### ISSUE THREAD

**Issue by gonssal** [mkxml/vscode-filesize#11]
This extension overwrites the core default "Format Document" shortcut on linux, "Ctrl + Shift + I"

**Comment by mkxml** [comment]
@gonssal Thank you for reporting. I was not aware of this problem. I will think of another shortcut and ship the change in the next release.

Can you give me a suggestion that would work great on VS Code for Linux?

**Comment by gonssal** [comment]
Considering it's for the current file, maybe "Ctrl + Shift + ."?

**Comment by mkxml** [comment]
@gonssal Can you check the `keybindings` file to see if `Ctrl+Shift+.` is not used to Relace with next value on text focus?

Because on mac `Cmd+Shift+.` does that.

If `Ctrl+Shift+.` is available we should use it for Mac as well.

I'm booting up VMs to check Windows too.

**Comment by gonssal** [comment]
"Replace with next value" is `Ctrl+Shift+<` in Linux. 

Before suggesting it, I checked if `Ctrl+Shift+.` was being used in Linux. I have all the default shortcuts.

**Comment by mkxml** [comment]
Unfortunately, `Ctrl+Shift+.` is "Replace with next value" on Windows. Just checked this.

Perhaps we can keep `Ctrl+Shift+I` on Windows and switch to `Ctrl+Shift+.` on Linux.

It would not be ideal but better than breaking core shortcuts on Linux, unless we find an universally available shortcut across platforms.

**Comment by gonssal** [comment]
I personally changed it to `Ctrl+Shift+ContextMenu`, but not sure how that would work on Macs.

**Comment by mkxml** [comment]
Used `Ctrl+Shift+'`. Thank you @gonssal! The new shortcut is available in `2.1.0`.
