### ISSUE TITLE
Add ability to see file size in bytes

### ISSUE THREAD

**Issue by BlakeTheAwesome** [mkxml/vscode-filesize#16]
It would be really good to have the option to see the file size in bytes, as there currently isn't a way to do that.
Ideally there would be a setting to change the status bar view, and the detailed view would show size/gzipped with abbreviated followed by actual:
`5.17Kib (5290 bytes)`

This would be useful when you need to know the actual size of a file and not just an approximation.

**Comment by mkxml** [comment]
I added this in the detailed view (after clicking), in version `3.2.1`, please check the setting option `Show Raw In Bytes`.
