### ISSUE TITLE
Display gzipped size in the status bar

### ISSUE THREAD

**Issue by stefanobartoletti** [mkxml/vscode-filesize#17]
It would be really useful to display the gzipped size of the current opened file in the status bar next to the uncompressed size, without having to click and open the panel.

I have in mind something like this: `20.65 KiB (5.17 KiB)`, where the first value is the actual uncompressed size, and inside the parentheses the gzipped value.

**Comment by dutzi** [comment]
Hey @mkxml, are you planning on adding this? I saw a commit related to it but it wasn't in master, is this a performance concern?

**Comment by mkxml** [comment]
@Masquerade-Circus PR was merged addressing this. I'll close this now.

**Comment by mkxml** [comment]
It will be on the next release.
