### ISSUE TITLE
Option to display on the right side of the status bar 

### ISSUE THREAD

**Issue by laurentpayot** [mkxml/vscode-filesize#24]
All file information (indentation, encoding, end of line, language) are displayed on the right side of the status bar. It should be the same for the size. Or at least give us the choice to display the size on the right or on the left with an option :wink:

**Comment by mkxml** [comment]
Hi @laurentpayot.

Sorry I took so long to review this. You're right, it should be an option in the settings for this.

I will work on this soon.

It should be present on the next release.

**Comment by Pustur** [comment]
Hey, thanks for including the option to change this 🙌

According to [this resource](https://code.visualstudio.com/api/references/extension-guidelines#status-bar) however, vscode devs recommend to:

- Place primary (global) items on the left
- Place secondary (contextual) items on the right

So I think by default the location should be on the right.
