### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by fakhamatia** [mkxml/vscode-filesize#27]
- Issue Type: `Performance`
- Extension Name: `vscode-filesize`
- Extension Version: `2.1.4`
- OS Version: `Linux x64 5.4.0-65-generic`
- VSCode version: `1.53.2`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

[mkxml.vscode-filesize-unresponsive.cpuprofile.txt](https://github.com/mkxml/vscode-filesize/files/6020031/mkxml.vscode-filesize-unresponsive.cpuprofile.txt)

**Comment by mkxml** [comment]
I implement bundling in version 3.0.0. Please test this one. Thank you.

**Comment by mkxml** [comment]
Closing for now, as 3.1.0 appears OK.

Please let me know if the problem persists.
