### ISSUE TITLE
Failed on VS code v1.54.1...

### ISSUE THREAD

**Issue by antkillerfarm** [mkxml/vscode-filesize#28]
After upgrade vs code today, a sad story happens...

**Comment by tyler36** [comment]
Not working for me either.

If I switch to the output panel and select debug, the output panels closes and won't open again (until I restart).
Tried version `2.1.4` (latest) and `1.1.0`

OS: Win10x64
Vscode: `1.54.1`
Filesize: `2.1.4` (latest)

**Comment by mkxml** [comment]
Yes, I can confirm it is broken on VS Code 1.54+

I will work on a fix tomorrow.

Hopefully I can release a new version tomorrow with the fix and other adjustments.

**Comment by mkxml** [comment]
Fixed on 3.0.0, please update and test this one. Thank you!

**Comment by tyler36** [comment]
Thanks ... VSCode marketplace page shows `3.0.0` but when I click the install button, it  opens the `2.1.4` version. 
Running `Check for extention updates` reports all extensions are up to date. Guess I have to give some time to replicated out.

**Comment by tyler36** [comment]
Confirmed. Working again 🎉 

Oh, and I like the new "right side of the statusbar option". Really nice
