### ISSUE TITLE
Publish to open-vsx.org?

### ISSUE THREAD

**Issue by hl2guide** [mkxml/vscode-filesize#31]
Please consider publishing this extension to: https://open-vsx.org/

So that users of VSCodium can use it too.

**Comment by mkxml** [comment]
Good idea, I will release a new version soon, than I will publish on both locations.

Thank you @hl2guide!

**Comment by mkxml** [comment]
Done, it's officially available on https://open-vsx.org/extension/mkxml/vscode-filesize
