### ISSUE TITLE
"Show Brotli" option does not work as expected

### ISSUE THREAD

**Issue by GoudronViande24** [mkxml/vscode-filesize#37]
This option in the settings:
![image](https://user-images.githubusercontent.com/42936037/150659378-b4012f8f-70fd-4334-b4a7-b9549f2aa64a.png)

When enabled, it does not show in status bar. I only have "Raw" and "Gzip".
When enabled, it does show up in detailed view, and when disabled, it doesn't. Maybe just the description is wrong?
I would like to have brotli compression in status bar since it is the compression used by almost all my projects once online.

Thank you!

**Comment by mkxml** [comment]
It's OK now in `3.2.1`, the output is like @nickchomey comment.
