### ISSUE TITLE
Great extension, doesnt work with dual panels though 🤔

### ISSUE THREAD

**Issue by matt3224** [mkxml/vscode-filesize#4]
Hey,

Can you add the ability for filesize to show the size of a file that is in the split editor?

Thanks
![screen shot 2017-05-24 at 10 22 48 am](https://cloud.githubusercontent.com/assets/2401925/26396372/f246d79c-406a-11e7-8f06-48e67a380208.png)

**Comment by mkxml** [comment]
Hi @matt3224, I noticed that a few days ago too.

The expected behavior is to show the size info for the current focused panel.

I will work on a fix soon.

Thanks for reporting this!

**Comment by alexdresko** [comment]
I came to the repo issues to find out why the size wasn't working as expected. This issue perfectly describes what I'm seeing.

**Comment by mkxml** [comment]
Sorry for the long delay, was focusing on other projects. This should be fixed in `1.1.0`. Please update. Thank you!
